var sysCities = {
    "fromcities": [
        {"name":"Boston, US", "id":"BOS"},
            {"name":"Chicago, US", "id":"ORD"},
            {"name":"Fort Lauderdale, US", "id":"FLL"},
            {"name":"Las Vegas, US", "id":"LAS"},
            {"name":"Los Angeles, US", "id":"LAX"},
            {"name":"Miami, US", "id":"MIA"},
            {"name":"New York, US", "id":"JFK"},
		{"name":"New Orleans, US", "id":"MSY"},
		{"name":"San Francisco, US", "id":"SFO"},
            {"name":"Orlando, US", "id":"MCO"},
            {"name":"Tampa, US", "id":"TPA"},
            {"name":"Washington Dulles, US", "id":"IAD"}    
    ],

    "tocities": [
     {"name":"Asuncion, PY","id": "ASU"},
            {"name":"Aruba, AW","id": "AUA"},
            {"name":"Barranquilla, CO", "id":"BAQ"},
            {"name":"Belo Horizonte, BR", "id":"CNF"},
            {"name":"Bogota, CO", "id":"BOG"},
            {"name":"Boston, US", "id":"BOS"},
            {"name":"Brasilia, BR", "id":"BSB"},
		{"name":"Belize, BZ", "id":"BZE"},
            {"name":"Bucaramanga, CO", "id":"BGA"}, 
		{"name":"Buenos Aires, AR", "id":"EZE"},
            {"name":"Cali, CO", "id":"CLO"},
            {"name":"Campinas, BR", "id":"VCP"},
            {"name":"Cancun, MX", "id":"CUN"},
            {"name":"Caracas, VE", "id":"CCS"},
            {"name":"Cartagena, CO", "id":"CTG"},
            {"name":"Chicago, US", "id":"ORD"},
		{"name":"Cordoba, AR", "id":"COR"},
            {"name":"Cucuta, CO", "id":"CUC"},
            {"name":"Curazao, AN", "id":"CUR"},
            {"name":"David, PA", "id":"DAV"},
            {"name":"Fort Lauderdale, US", "id":"FLL"},
            {"name":"Guadalajara, MX", "id":"GDL"},
		{"name":"Guayaquil, EC", "id":"GYE"},
            {"name":"Guatemala, GT", "id":"GUA"},
		{"name":"Georgetown, GY", "id":"GEO"},
            {"name":"Iquitos, PE", "id":"IQT"},
            {"name":"Kingston, JM", "id":"KIN"},
            {"name":"La Habana, CU", "id":"HAV"},
            {"name":"Liberia, CR", "id":"LIR"},
            {"name":"Lima, PE", "id":"LIM"},
		{"name":"Los Angeles, US", "id":"LOS"},
            {"name":"Managua, NI", "id":"MGA"},
            {"name":"Manaus, BR", "id":"MAO"},
            {"name":"Medellin, CO", "id":"MDE"},
            {"name":"Mexico City, MX", "id":"MEX"},
            {"name":"Miami, US", "id":"MIA"},
            {"name":"Montego Bay, JM", "id":"MBJ"},
            {"name":"Monterrey, MX", "id":"MTY"},
            {"name":"Montevideo, UY", "id":"MVD"},
            {"name":"Montreal, CA", "id":"YUL"},
            {"name":"Nassau, BS", "id":"NAS"},
		{"name":"New York, US", "id":"JFK"},
            {"name":"New Orleans, US", "id":"MSY"},
            {"name":"Orlando, US", "id":"MCO"},
            {"name":"Panama, PA", "id":"PTY"},
            {"name":"Pereira, CO", "id":"PEI"},
            {"name":"Porto Alegre, BR", "id":"POA"},
		{"name":"Puebla, MX", "id":"PBC"},
            {"name":"Port of Spain, TT", "id":"POS"},
		{"name":"Port Au Prince, HT", "id":"PAP"},
            {"name":"Punta Cana, DO", "id":"PUJ"},
		{"name":"Quito, EC", "id":"UIO"},
            {"name":"Recife, BR", "id":"REC"},
            {"name":"Rio de Janeiro, BR", "id":"GIG"},
            {"name":"San Andres Island, CO", "id":"ADZ"},
            {"name":"San Jose, CR", "id":"SJO"},
            {"name":"San Juan, PR", "id":"SJU"},
            {"name":"San Pedro Sula, HN", "id":"SAP"},
            {"name":"San Salvador, SV", "id":"SAL"},
            {"name":"Santiago de Chile, CL", "id":"SCL"},
            {"name":"Santiago de los Caballeros, DO", "id":"STI"},
            {"name":"Santa Cruz, BO", "id":"VVI"},
            {"name":"Santa Clara, CU", "id":"SNU"},
            {"name":"Santo Domingo, DO", "id":"SDQ"},
		{"name":"San Francisco, US", "id":"SFO"},
            {"name":"Sao Paulo, BR", "id":"GRU"},
            {"name":"St Maarten, AN", "id":"SXM"},
            {"name":"Tampa, US", "id":"TPA"},
            {"name":"Tegucigalpa, HN", "id":"TGU"},
            {"name":"Toronto, CA", "id":"YYZ"},
            {"name":"Valencia, VE", "id":"VLN"},
		{"name":"Villahermosa, MX", "id":"VSA"},
            {"name":"Washington Dulles, US", "id":"IAD"}
    ]
},

departure_date = new Date(2016, 03 - 1, 15),
return_date = new Date(2016, 06 - 1, 30),

// Mensajes de error para el booking
msj = {
      en: {
            city_origin_null: "Select a city of origin",    
            destination_city_null: "Select the destination city",
            origin_destination: "The destination city should be different from the city of origin",
            departure_date: "Select departure",
            return_date: "Select Return Date"
      },
      es: {
            city_origin_null: "Seleccione la ciudad de origen",
            destination_city_null: "Seleccione la ciudad de destino",
            origin_destination: "La ciudad de destino debe ser diferente de la de origen",
            departure_date: "Seleccione la fecha de salida",
            return_date: "Seleccione la fecha de regreso"
      },
      pt: {
            city_origin_null: "Selecione uma cidade de origem",
            destination_city_null: "Selecione a cidade de destino",
            origin_destination: "A cidade de destino deve ser diferente a partir da cidade de origem",
            departure_date: "Selecione a partida",
            return_date: "Selecionar data de retorno"
      }
};